import type { Metadata } from "next";
import { Reem_Kufi } from "next/font/google";

import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";


const reemKufi = Reem_Kufi({
  subsets: ["latin"],
  weight: ["400", "700"], // Include the weights you want
  variable: "--font-reem-kufi", // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${reemKufi.variable} font-sans flex flex-col `}>
        <div className="bg-gray-100 w-screen h-screen"> 
          <h2>ccc</h2>
        </div>
        <SidebarProvider>
          <AppSidebar />
          {/* <SidebarTrigger /> */}
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
